### PR TITLE
Refactoring of LuaRef to push function parameters on the stack in a generic way

### PR DESCRIPTION
**Pull request by stefanfrings**

### CODE REVIEW

**Comment by dmitry-t** [comment]
Well done!
This what I really was dreaming about.
On which platforms did you test this?

**Comment by stefanfrings** [comment]
The change is compliant to the C++ 11 standard and therefore I don't expect any portability issues.
Nevertheless I have tested it with other platforms as well because of your concerns. Build and tests were successful on these platforms.
- g++ 10.3.0 (mingw), 64 Bit, Windows 10
- g++ 8.3.0, 64 Bit, Linux
- VisualStudio 2017, 32 and 64 Bit, Windows 10

Do you face any issues?

**Comment by dmitry-t** [comment]
Let me try on Linux (gcc, clang).

**Comment by dmitry-t** [comment]
Tested on
- g++ 9.3.0, Linux
- clang 6.0.1-14, Linux
- MSVS 2019, 32 bit, Windows

For Win32 I get the build errors (same error twice - for 2 test apps):
```
11>...\Tests\Source\NamespaceTests.cpp(320,69): error C2664: 'luabridge::Namespace &luabridge::Namespace::addFunction(const char *,int (__cdecl *const )(lua_State *))': cannot convert argument 2 from 'int (__stdcall *)(int)' to 'int (__cdecl *const )(lua_State *)'
11>...\Tests\Source\NamespaceTests.cpp(320,61): message : This conversion requires a reinterpret_cast, a C-style cast or function-style cast
11>...\Source\LuaBridge/detail/Namespace.h(1305,16): message : see declaration of 'luabridge::Namespace::addFunction'
12>...\Tests\Source\NamespaceTests.cpp(320,69): error C2664: 'luabridge::Namespace &luabridge::Namespace::addFunction(const char *,int (__cdecl *const )(lua_State *))': cannot convert argument 2 from 'int (__stdcall *)(int)' to 'int (__cdecl *const )(lua_State *)'
12>...\Tests\Source\NamespaceTests.cpp(320,61): message : This conversion requires a reinterpret_cast, a C-style cast or function-style cast
12>...\Source\LuaBridge/detail/Namespace.h(1305,16): message : see declaration of 'luabridge::Namespace::addFunction'

**Pull request merged**
