### PR TITLE
Add std::optional integration

### PR DESCRIPTION
**Pull request by stefanfrings**

### CODE REVIEW

**Review by dmitry-t — APPROVED** [review]

**Comment by dmitry-t** [comment]
Are there other issues to solve before the merge?

**Comment by stefanfrings** [comment]
@dmitry-t It's complete

**Comment by amitma1** [comment]
I might be talking nonsense here, but I believe `std::optional` should have another specialization for `std::optional<T>&`.
In case we try to push an `std::optional`, we want to pass down the usage of reference to the next `Stack<>::Push`
maybe something like:
```
const auto & ref = optional.value();
Stack<decltype(ref)>::push(L, ref);
```
?

**Comment by stefanfrings** [comment]
I would say no, because the template parameter `T` doesn't define how the value is passed to the next `Stack<T>::push(...)` function. This only depends on the particular stack specialization.

For instance, if `T` is an integer the parameter is passed by value.
https://github.com/vinniefalco/LuaBridge/blob/36c0c62815f9f6bf43c81a3977502cd3996302a0/Source/LuaBridge/detail/Stack.h#L60

On the other hand if `T` is _expensive_ to copy it's passed by reference.
https://github.com/vinniefalco/LuaBridge/blob/36c0c62815f9f6bf43c81a3977502cd3996302a0/Source/LuaBridge/detail/Stack.h#L333

**Comment by amitma1** [comment]
What's happening in case it's a User data (like a defined class)?
How can we infer if it's expensive to copy or not?
Does it assume "expensive"?

**Comment by stefanfrings** [comment]
In case of custom/user defined types you have to provide a corresponding stack specialization.
See chapter **2.7 Lua Stack** of the manual: http://vinniefalco.github.io/LuaBridge/Manual.html#s2.7

By providing the specialization you have to decide if T is _cheap_ or _expensive_ to copy.

As a rule of thumb you can roughly say, pass simple types (int, float, char, pointers, ...) by value and all others by reference.
For more details see the trivially copyable concept of C++: https://en.cppreference.com/w/cpp/named_req/TriviallyCopyable
But at the end the decision also heavily depends on the compiler and the target platform

**Pull request merged**
